<?php echo $this->render('header/headerReport.phtml');?>

<!-- ====================================== -->
<!-- inicio : específico para cada template -->					
<!-- ====================================== -->						  
	<div>
		<table class="withoutEdge" width="100%">
			<tr>
				<td align="center">
					<?php echo $this->render('report/_form.phtml');?>
				</td>
			</tr>
		</table>
	</div>																  
<!-- =================================== -->
<!-- fim : específico para cada template -->					
<!-- =================================== -->		
					
<?php echo $this->render('footer/footerReport.phtml');?>