<?php echo $this->render('header/header.phtml');?>
<?php echo $this->render('submenu/submenuPerson.phtml');?>
<table width="60%" class="withoutEdge">
	<tr>
		<td class="middleValign" width="15%" align="right">
			<img src="<?php echo $this->baseUrl;?>/public/styles/alert.jpg"/>
		</td>
		
		<td width="85%" align="center">
			<h1>
				<?php echo ($this->labels->confirm->end->title);?>
			</h1>

			<?php printErrorsByField($this->form->assistanceId(), $this->errorMessages);?>
			<form action="<?php echo $this->baseUrl;?><?php echo ATTENDANCE_CONTROLLER;?>/<?php echo $this->action;?>" method="post">
				<p>
					<?php echo $this->labels->confirm->end->text;?>
					<br/>
					<?php 
						$assistance = $this->assistance;
						$description = $assistance[Constants::AST_SUMMARY_DESC];
					?>
					<?php if($assistance[Constants::AST_SUMMARY_TYPE] == Constants::ESPECIAL): ?>
						<?php echo $this->controller->attendance->text->especial; ?>
		
					<?php elseif($description): ?>
						<?php echo $description; ?>
		
					<?php else: ?>
						<?php echo $this->controller->attendance->text->attendance; ?>
						
					<?php endif; ?>
				</p>

				<div>
					<input type="hidden" name="<?php echo $this->form->assistanceId();?>" value="<?php echo $assistance[Constants::AST_SUMMARY_ID];?>" />
					<input type="hidden" name="<?php echo $this->form->personId();?>" value="<?php echo $this->form->getPersonId();?>" />
					<input type="hidden" name="<?php echo $this->form->classId();?>" value="<?php echo $this->form->getClassId();?>" />
				  	<input type="submit" name="" value="<?php echo $this->labels->confirm->button->yes;?>" />
				  	<input type="submit" name="" value="<?php echo $this->labels->confirm->button->cancel;?>" 
				  	onClick="javascript: return actionName('<?php echo $this->baseUrl;?><?php echo ATTENDANCE_CONTROLLER;?>/<?php echo DEFAULT_ATTENDANCE_ACTION;?>',this.form);"/>
				</div>
			</form>			
		</td>
	</tr>
</table>

<?php echo $this->render('footer/footer.phtml');?>
 

