<?php echo $this->render('header/header.phtml');?>								 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuPerson.phtml');?>

	<?php echo $this->render('success/_success.phtml');?>
	<a href="<?php echo $this->baseUrl . ATTENDANCE_CONTROLLER.'/'.DEFAULT_ATTENDANCE_ACTION.'/'.$this->form->personId().'/'.$this->form->getPersonId();?>">
		<?php echo $this->labels->button->back; ?>
	</a>
</div>																  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/footer.phtml');?>


