<?php echo $this->render('header/header.phtml');?>										 		  						
									  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuPerson.phtml');?>

	<!-- ============================================================================================== -->
	<!-- É necessário informar o nome class da tabela em questão para carregar a cor background correta -->
	<!-- Opções: 
				#identification
				#person
				#education
				#health
				#income
				#familyRelationship
				#residence
				#attendance
				#activity	-->
	<!-- ============================================================================================== -->
	<table class="attendance" width="98%">
		<?php if($this->errorMessages[$this->form->assistanceId()]):?>
			<tr><td align="center"><?php printErrorsByField($this->form->assistanceId(), $this->errorMessages);?></td></tr>		
		<?php elseif($this->errorMessages[$this->form->personId()]):?>
			<tr><td align="center"><?php printErrorsByField($this->form->personId(), $this->errorMessages);?></td></tr>
		<?php elseif($this->errorMessages[$this->form->classId()]):?>
			<tr><td align="center"><?php printErrorsByField($this->form->classId(), $this->errorMessages);?></td></tr>
		<?php else:?>			
			<tr>
				<td align="center">	
					<?php 
						echo $this->render('attendance/_groupForm.phtml'); // especial
					?>					
				</td>
			</tr>
		<?php endif;?>
	</table>
</div>																  
<!-- =================================== -->
<!-- fim : específico para cada template -->					
<!-- =================================== -->		
					
<?php echo $this->render('footer/footer.phtml');?>	