<?php echo  $this->render('header/header.phtml');?>
<br><br><br>
<table class="noBorder" width="60%">
	<tr>
		<td class="alignLeft">
			<?php echo  $this->helpcontroller->text4?><b><?php echo  $this->helpcontroller->text2?></b>
			<p>
			<?php echo  $this->helpcontroller->text5?>
			<p>
			<b class="greenWrite"><?php echo  $this->helpcontroller->text6?></b>
		</td>
	</tr> 
</table>
<br><br><br><br>
<?php echo  $this->render('footer/footer.phtml');?>
