<?php echo $this->render('header/headerAuth.phtml');?>
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->		

<table class="withoutEdge" align="center">
	<tr>
		<td>
			<?php echo $this->render('auth/_form.phtml');?>
		</td>
	</tr>
</table>

<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/foot.phtml');?>