<?php echo $this->render('header/headerAuth.phtml');?>								 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->

<?php echo $this->render('auth/_form.phtml');?>

<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/foot.phtml');?>