<table class="withoutEdge" width="100%">
	<tr class="write">
		<td align="right">
			|&nbsp;&nbsp;<a href="<?php echo  $this->baseUrl;?><?php echo  AREA_CONTROLLER;?>/<?php echo  DEFAULT_INDEX_ACTION;?>"><?php echo  $this->labels->button->admin->entity->expertisearea;?></a>&nbsp;&nbsp;
			|&nbsp;&nbsp;<a href="<?php echo  $this->baseUrl;?><?php echo  CLASSIFICATION_CONTROLLER;?>/<?php echo  DEFAULT_INDEX_ACTION;?>"><?php echo  $this->labels->button->admin->entity->classification;?></a>&nbsp;&nbsp;
			|&nbsp;&nbsp;<a href="<?php echo  $this->baseUrl;?><?php echo  PROGRAM_CONTROLLER;?>/<?php echo  DEFAULT_INDEX_ACTION;?>"><?php echo  $this->labels->button->admin->entity->typeprogram;?></a>&nbsp;&nbsp;
			|&nbsp;&nbsp;<a href="<?php echo  $this->baseUrl;?><?php echo  ACTIVITY_CONTROLLER;?>/<?php echo  DEFAULT_INDEX_ACTION;?>"><?php echo  $this->labels->button->admin->entity->activity;?></a>&nbsp;&nbsp;
		</td>
	<tr>
</table>
<br>

