<table class="withoutEdge" width="100%">
	<tr class="write">
		<td align="center">																												
			|&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->profile;?></a>&nbsp;&nbsp;
			|&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo GROUP_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->group;?></a>&nbsp;&nbsp;
			|
		</td>
	<tr>
</table>
<br>