<table class="withoutEdge" width="100%">
	<tr class="write">
		<td align="left">																												
			|&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->region;?></a>&nbsp;&nbsp;
			|&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->permission;?></a>&nbsp;&nbsp;
			|&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo ADDITIONALINFORMATION_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->additional;?></a>&nbsp;&nbsp;
			|&nbsp;&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo IMPORT_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->title->import;?></a>&nbsp;&nbsp;
			|
		</td>
	<tr>
</table>
<br>