<?php echo $this->render('header/header.phtml');?>								 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuEntity.phtml');?>
	
	<!-- ============================================================================================== -->
	<!-- É necessário informar o nome class da tabela em questão para carregar a cor background correta -->
	<!-- Opções: 
				#identification
				#person
				#education
				#health
				#income
				#familyRelationship
				#residence
				#attendance
				#activity	-->
	<!-- ============================================================================================== -->
	<table class="entity" width="98%">
		<tr>
			<td class="bold">
			<form>
				<?php echo $this->render(SEARCHADDRESS_CONTROLLER.'/iframe_search.phtml');?>
				<?php echo $this->render(SEARCHADDRESS_CONTROLLER.'/_address.phtml');?>
			</form>
			</td>
		</tr>
	</table>
</div>																  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/footer.phtml');?>