<html>

<?php echo $this->render('header/head.phtml');?>

<body>
	<div class="alignDivCenter"> 
		<table class="withOutEdge" width="980">
			<tr>
				<td>
					<?php echo $this->render('header/authBar.phtml');?>
					<?php echo $this->render('menu/menu.phtml');?>
					<table class="withoutEdge" width="100%">
						<tr>
							<td width="100%" align="center">
							
							<!-- ============= -->
							<!-- fim do header -->
							<!-- ============= -->