<?php
/*
 * Created on 19/03/2008
 * Author: Jefferson
 */
?>
	<!-- FORMULARIO DE IMPORTACAO DE CAD UNICO -->
	<form id="importSingleFrm" method="post" enctype="multipart/form-data">
	<div id="importSingleDiv" style="<?php if($this->form->getRadioButton()== 'single')echo 'display:inline'; else echo 'display:none'; ?>">
		<input type="hidden" name="<?php echo $this->form->radioButton()?>" value="<?php echo ImportForm::SINGLEREGISTER_DIV_KEY;?>"/>
		<table width="100%" >
			<tr>
				<td colspan="2">
					<h1><?php echo $this->controller->import->title->import;?></h1>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<?php /* Mensagem de erro ao carregar o arquivo */ 
						foreach($this->singleInfos as $info)
							foreach($info->getMessage() as $msg)
								printError( $msg );
					?>
				</td>
			</tr>
			<tr>
				<?php if($this->processSingleRegister) { ?>				
			</tr>
			<tr>
				<td colspan="2" align="center">
					<?php printErrorsByField(Constants::PROCESS_KEY, $this->errorSingleMessages);?>
				</td>
				<?php if(!$this->errorSingleMessages):?>
				</tr>
				<tr>	
					<td colspan="2"><?php echo $this->helpcontroller->wait;?></td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="submit" value="<?php echo $this->controller->button->process;?>" 
						onClick="javascript: actionName('<?php echo $this->baseUrl;?><?php echo IMPORT_CONTROLLER;?>/<?php echo PROCESS_SINGLEREGISTER_ACTION;?>',this.form);this.form.submit();this.disabled=true;"
						<?php if($this->errorSingleMessages)echo 'disabled';?> />
					</td>
				<?php endif;?> 
				<?php }	else { // Caso seja necessário algum arquivo ?>
				<td colspan="2">
					<b><?php echo $this->controller->import->text->searchFile;?>:</b><br>
					<?php printErrorsByField(ImportForm::addressFile(), $this->errorSingleMessages);?>
					<?php printErrorsByField(ImportForm::folder(), $this->errorSingleMessages);?>
				</td>
			</tr>
			<tr>
				<td colspan="2"><?php echo $this->helpcontroller->single1;?><p></td>
			</tr>
			<tr>
				<td colspan="2">
					<input type="hidden" name="<?php echo ImportForm::folder();?>" value="<?php if($this->singleUpload) echo $this->singleUpload->getFolderName();?>">
					<input type="file" name="<?php echo ImportForm::addressFile();?>" value="" <?php if(!$this->singleInfos)echo 'disabled';?> >
				</td>
			</tr>
			<tr>
				<td>
					<input type="submit" value="<?php echo $this->controller->button->import;?>" 
					onClick="javascript: actionName('<?php echo $this->baseUrl;?><?php echo IMPORT_CONTROLLER;?>/<?php echo DEFAULT_SINGLEREGISTER_ACTION;?>',this.form);"
					<?php if(!$this->singleInfos)echo 'disabled';?>>
				</td>
				<?php }// end ELSE  (Don´t delete the '}') ?>
			</tr>
		</table>
	</div>
	</form>
