<?php echo $this->render('header/header.phtml');?>										 		  						
									  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuAdm.phtml');?>
	<!-- ============================================================================================== -->
	<!-- É necessário informar o nome class da tabela em questão para carregar a cor background correta -->
	<!-- Opções: 
				#identification
				#person
				#education
				#health
				#income
				#familyRelationship
				#residence
				#attendance
				#activity	-->
	<!-- ============================================================================================== -->
	<table class="report" width="98%">
		<tr>
			<td align="center">
				<?php echo $this->render('navigation/navigationSetup.phtml');?>
			</td>
		</tr>
		<tr>
			<td align="center">
				<?php
					$msgs =$this->processMsg;
					if($this->errorMessages && count($this->errorMessages) > 0)
					{
						echo $this->render('import/_form.phtml');
					}
					else 
					{ // Start ELSE
						if($msgs === NULL)
							echo $this->render('import/unsuccess.phtml');
						else if(!empty($msgs) && count($msgs) > 0)
						{
							echo $this->render('success/_success.phtml');
							
							echo $this->controller->import->text->importErrorMsg;
							foreach($msgs as $msg)
								echo '<br/>'.$msg;
						}
					?>
						<p>
							<a href="<?php echo $this->baseUrl;?><?php echo IMPORT_CONTROLLER.'/'.DEFAULT_INDEX_ACTION;?>">Voltar</a>
						</p>
					<?php }// End ELSE ?>
			</td>
		</tr>
	</table>
</div>																  
<!-- =================================== -->
<!-- fim : específico para cada template -->					
<!-- =================================== -->		
					
<?php echo $this->render('footer/footer.phtml');?>	