<?php echo $this->render('header/header.phtml');?>								 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuEntity.phtml');?>
	
	<table class="activity" width="98%" >
		<?php 
			if(!$this->errorMessages)
			{
				echo $this->render('success/_success.phtml');
			}
			else
			{	
				echo $this->render('class/invalidParam.phtml');
			}
		?>
	</table>
	
</div>																  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/footer.phtml');?>
