<?php
/*
 * 
 * Created on 19/02/2008 
 * W3S Solutions by Fabricio Meireles Monteiro
 * 
 */
?>
<?php echo $this->render('header/header.phtml');?>

<table width="98%" class="withoutEdge">
	<?php 
		if(!$this->errorMessages)
		{
			echo $this->render('class/migrate.phtml');
		}
		else
		{
			echo $this->render('class/invalidParam.phtml');
		}
	?>
</table>
<?php echo $this->render('footer/footer.phtml');?>
 

