<?php echo $this->render('header/header.phtml');?>								 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuEntity.phtml');?>
	
	<table class="activity" width="98%" >
		<?php echo $this->render('class/edit_form.phtml');?>
	</table>
	
</div>																  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		
<br>
<?php echo $this->render('footer/footer.phtml');?>
