<table width="100%">
	<form action="<?php echo $this->baseUrl;?><?php echo BIOLOGICALRELATIONSHIP_CONTROLLER;?>/<?php echo DEFAULT_ADD_ACTION;?>" method="post">
		<input type="hidden" name="<?php echo SearchForm::idPerson();?>" value="<?php echo $this->form->getIdPerson();?>"/>
		<?php printErrorsByField($this->form->idPerson(), $this->errorMessages);?>
		<tr>
			<td>
				<h1><?php echo $this->controller->bioRelation->text->result?></h1>
			</td>
		</tr>
		<tr>
			<td align="right" height="30">
				|<a href="<?php echo $this->baseUrl;?><?php echo BIOLOGICALRELATIONSHIP_CONTROLLER;?>/<?php echo DEFAULT_SEARCH_ACTION;?>/<?php echo SearchForm::idPerson();?>/<?php echo $this->form->getIdPerson();?>"><?php echo $this->controller->bioRelation->result->newSearch;?></a>&nbsp;|
				<a href="<?php echo $this->baseUrl;?><?php echo PERSON_CONTROLLER;?>/<?php echo DEFAULT_NEW_ACTION;?>/<?php echo SearchForm::idPerson();?>/<?php echo $this->form->getIdPerson();?>"><?php echo $this->controller->bioRelation->result->newPerson;?></a>&nbsp;|
			</td>
		</tr>
		<?php 
			if($this->form->getDocNumber() != null && strlen($this->form->getDocNumber()) > 0 )
			{	
				$paramSearch = $this->form->getDocNumber();
			}
			elseif($this->form->getPrsName() != null && strlen($this->form->getPrsName()) > 0)
			{	
				$paramSearch = $this->form->getPrsName();
			}
			else
			{
				$paramSearch = $this->controller->bioRelation->searchempty;
			}
			
			$countMan = 0;
			$countWoman = 0;
			
			if($this->resultSearchByDocument)
			{	
				foreach($this->resultSearchByDocument as $unique)
				{
					if($unique->findParentRow(CLS_PERSON)->{PRS_SEX} == 'f')
					{
						$countWoman ++;
					}
					
					if($unique->findParentRow(CLS_PERSON)->{PRS_SEX} == 'm')
					{	
						$countMan ++;
					}
				}
			}
			else
			{	
				foreach($this->resultSearchByName as $unique)
				{
					if($unique->{PRS_SEX} == 'f')
					{
						$countWoman ++;
					}
					
					if($unique->{PRS_SEX} == 'm')
					{	
						$countMan ++;
					}
				}
			}
		
			
			if($countMan != 0)
			{
				echo "<tr>";
					echo "<td height='20'>";
							echo "<table class='withOutEdge'>";
								echo "<tr>";
									echo "<td>";
										echo $this->controller->bioRelation->result->info1;
										echo "<b>";
										echo "&nbsp;".$countMan;
										echo "</b>&nbsp;";
										echo $this->controller->bioRelation->result->info2;
										echo "<b>&nbsp;";
										echo $this->controller->bioRelation->text->man;
										echo "</b>&nbsp;";
										echo $this->controller->bioRelation->result->info3;
										echo "<b>&nbsp;";
										echo $paramSearch;
										echo "</b>";
										echo ".&nbsp;";
										echo $this->controller->bioRelation->result->info4;
									echo "</td>";
								echo "</tr>";
							echo "</table>";
							echo "<br>";
					echo "</td>";
				echo "</tr>";
			}
			
			
			if($countWoman != 0)
			{
				echo "<tr>";
					echo "<td height='20'>";
							echo "<table class='withOutEdge'>";
								echo "<tr>";
									echo "<td>";
										echo $this->controller->bioRelation->result->info1;
										echo "<b>";
										echo "&nbsp;".$countWoman;
										echo "</b>&nbsp;";
										echo $this->controller->bioRelation->result->info2;
										echo "<b>&nbsp;";
										echo $this->controller->bioRelation->text->woman;
										echo "</b>&nbsp;";
										echo $this->controller->bioRelation->result->info3;
										echo "<b>&nbsp;";
										echo $paramSearch;
										echo "</b>";
										echo ".&nbsp;";
										echo $this->controller->bioRelation->result->info4;
									echo "</td>";
								echo "</tr>";
							echo "</table>";
							echo "<br>";
					echo "</td>";
				echo "</tr>";
			}
			
			if($countWoman == 0 && $countMan == 0)
			{
				echo "<tr>";
					echo "<td colspan='2' height='20'>";
							echo "<table class='withOutEdge'>";
								echo "<tr>";
									echo "<td>";
										echo $this->controller->bioRelation->notfound;
										echo "&nbsp;<b>";
										echo $paramSearch;
										echo "</b>";
										echo ".";
									echo "</td>";
								echo "</tr>";
							echo "</table>";
							echo "<br>";
					echo "</td>";
				echo "</tr>";
			}
			
			$countLine = 0;
			if($this->resultSearchByDocument)
			{	
				foreach($this->resultSearchByDocument as $unique)
				{
					echo "<tr>";
						echo "<td>";
							echo "<table width='100%' class='withOutEdge'>";	
								if(($countLine%2) == 0) echo "<tr class='write'>"; else echo "<tr>";
									echo "<td>";
										echo "<input type='radio' name='";
										echo SearchForm::idParent();
										echo "' value='";
										echo $unique->findParentRow(CLS_PERSON)->{PRS_ID_PERSON};
										echo "'/>";
										echo $unique->findParentRow(CLS_PERSON)->{PRS_NAME};
									echo "</td>";
								echo "</tr>";
							echo "</table>";
						echo "</td>";
					echo "</tr>";
					$countLine ++;
				}
			}
			else
			{
				foreach($this->resultSearchByName as $unique)
				{
					echo "<tr>";
						echo "<td>";
							echo "<table width='100%' class='withOutEdge'>";
								if( ($countLine%2) == 0) echo "<tr class='write'>"; else echo "<tr>";
									echo "<td colspan='2'>";
										echo "<input type='radio' name='";
										echo SearchForm::idParent();
										echo "' value='";
										echo $unique->{PRS_ID_PERSON};
										echo "'/>";
										echo $unique->{PRS_NAME};
									echo "</td>";
								echo "</tr>";
							echo "</table>";
						echo "</td>";
					echo "</tr>";
					$countLine ++;
				}
			}		
		?>
		
		<?php if($countWoman != 0 || $countMan != 0):?>
		<tr class='writeRed'>
			<td>
				<table class='withOutEdge' width="100%">
					<tr>
						<td width="62%" height="40" class="middleValign">
							<?php echo $this->controller->bioRelation->result->searchRelation;?>
						</td>
						<td height="38%" class="middleValign">
							<select name="<?php echo SearchForm::idkinship();?>">
								<option value=""><?php echo $this->labels->text->select;?>...</option>
								<?php 
									foreach($this->kinship as $kinship)
									{
										echo "<option value='";
										echo $kinship->{CTP_ID_CONSAGUINE_TYPE};
										echo "'>";
										echo $kinship->{CTP_DESCRIPTION};
										echo "</option>";		
									}
								?>
							</select>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td>
				<table class="withOutEdge" width="100%"><br>
					<tr>
						<td class="alignCenter">
							<input type="submit" value="<?php echo $this->labels->button->save;?>"/>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<?php endif; ?>
	</form>
</table>