
<tr>
	<td class="bold">
		<table width="100%" class="withoutEdge">
			<tr>
				<td>
					<h1><?php echo $this->labels->create->activity;?></h1>
				<hr></td>
			</tr>
			<tr>
				<td><?php echo $this->helpcontroller->text1?><hr></td>
			</tr>
			<tr>
				<td align="right">
					<?php echo $this->render('navigation/navigationEntity.phtml');?>
				</td>
			</tr>
		</table>
		
		<table width="100%" class="borderBlack">
			<tr>
				<td colspan="5" height="30">
					<h1><?php echo $this->controller->program->text->descriptionregister;?></h1>
				</td>
			</tr>
			
			<!-- =================================================================================================================== -->
			<!-- ============= FORM utilizado para persistir um programa:  salvar e editar um programa ============================= -->
			<!-- =================================================================================================================== -->
			<form action="<?php echo $this->baseUrl;?><?php echo PROGRAM_CONTROLLER;?>/<?php if($this->escape($this->form->getId()) != null){echo DEFAULT_EDIT_ACTION;}else{echo DEFAULT_ADD_ACTION;}?>" method="post">
				<tr>
					<td colspan="5" height="30">
						<?php echo $this->helpcontroller->text2?>
					</td>
				</tr>
				<tr>
					<td width="22%" align="right"><b><?php echo $this->controller->program->text->typeexpertise;?>:</b></td>
					<td width="28%">
						<input type="hidden" name="<?php echo $this->form->id();?>" value="<?php echo $this->escape($this->form->getId());?>"/>
						<input type="text" size="30" name="<?php echo ProgramForm::programName();?>" value="<?php echo $this->escape($this->form->getProgramName());?>" />
					</td>
					<td width="20%">
						<select name="<?php echo ProgramForm::idTargetPublic();?>">
							<option value=""><?php echo $this->controller->program->text->objectpublictarget;?></option>
							<?php 
								foreach($this->targetPublic as $uniquePublic)
								{
									echo "<option value='".$uniquePublic->{TMK_ID_TARGET_MARKET}."'";
											if($uniquePublic->{TMK_ID_TARGET_MARKET} == $this->escape($this->form->getIdTargetPublic()))
											{
												echo "selected>"; 	
											}	
											else
											{
												echo ">";	
											}
											echo $uniquePublic->{TMK_TARGET_MARKET}.
										"</option>";
								}
							?>				
						</select>						
					</td>
					<td width="20%">
						<select name="<?php echo $this->form->status();?>">
							<option value="<?php echo Constants::ENABLE;?>"><?php echo $this->labels->text->enable;?></option>
							<option value="<?php echo Constants::DISABLE;?>" <?php if($this->form->getStatus() == Constants::DISABLE) echo "selected";?>><?php echo $this->labels->text->disable;?></option>
						</select>
					</td>
					<td width="10%">
						<input class="small" type="submit" value="<?php echo $this->labels->button->save;?>"/>
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>
						<?php printErrorsByField($this->form->programName(), $this->errorMessages);?>
						
					</td>
					<td colspan="2">
						<?php printErrorsByField($this->form->idTargetPublic(), $this->errorMessages);?><br>
						<?php printErrorsByField($this->form->status(), $this->errorMessages);?>
					</td>
					
				</tr>
				
			</form>
			<!-- =================================================================================================================== -->
			<!-- ===================================================== fim do FORM ================================================= -->
			<!-- =================================================================================================================== -->
		</table>
		<br><br>
	</td>
</tr>

<tr>
	<td class="bold">
		<table class="borderBlack" width="100%">
			<!-- =================================================================================================================== -->
			<!-- ============== FORM utilizado para carregar um ou mais programas para ser excluído ================================ -->
			<!-- ================== FORM utilizado para carregar um programaa para ser excluído ==================================== -->
			<!-- =================================================================================================================== -->
			<form id="<?php echo PROGRAM_FORM;?>" method="post">
				<tr>
					<td width="22%" align="right"><b><?php echo $this->controller->program->text->registeredprogram;?>:</b></td>
					<td width="78%">
						<select id="typeProgram" name="<?php echo $this->form->id();?>[]" size="10" multiple>
							<?php 
								foreach($this->programs as $program)
								{	
									$targetMarket = $program -> findParentRow(CLS_TARGETMARKET); 
									echo "<option value='".$program->{PGT_ID_PROGRAM_TYPE}."' title='".$program->{PGT_PROGRAM_TYPE}.': '.$targetMarket -> {TMK_TARGET_MARKET}."'>".$program->{PGT_PROGRAM_TYPE}."&nbsp;:&nbsp;";
									echo $targetMarket -> {TMK_TARGET_MARKET}."&nbsp;";
									if($program->{PGT_STATUS} == Constants::DISABLE)
										echo "&nbsp;*&nbsp;".$this->labels->text->disable."&nbsp;*";
									echo"</option>";
								}
							?>
						</select>
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td class="alignLeft">
						<input type="submit" value="<?php echo $this->labels->button->edit;?>" 
						onClick="javascript: return reportMultipleSelected('<?php echo $this->baseUrl;?><?php echo PROGRAM_CONTROLLER;?>/<?php echo DEFAULT_VIEW_ACTION;?>',this.form, 'typeProgram');">&nbsp;
						<input type="submit" value="<?php echo $this->labels->button->disable;?>" 
						onClick="javascript: return actionName('<?php echo $this->baseUrl;?><?php echo PROGRAM_CONTROLLER;?>/<?php echo DEFAULT_CONFIRM_ACTION;?>',this.form);">
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>
						<?php printErrorsByField($this->form->id(), $this->errorMessages);?>
					</td>
				</tr>
			</form>
			<!-- =================================================================================================================== -->
			<!-- ===================================================== fim do FORM ================================================= -->
			<!-- =================================================================================================================== -->
		</table>
	</td>
</tr>