<tr>
	<td width="100%" align="center">
		<h1>
			<?php echo ($this->labels->confirm->disable->title);?>
		</h1>
		<!-- =================================================================================================================== -->
		<!-- =================================== FORM utilizado para excluir um ou mais perfil ================================= -->
		<!-- =================================================================================================================== -->
		<form action="<?php echo $this->baseUrl;?><?php echo PROGRAM_CONTROLLER;?>/<?php echo $this->action;?>" method="post">
			<p>
				<?php echo $this->labels->confirm->disable->text;?>&nbsp;?<br>
				<?php 
					foreach($this->objectPrograms as $program)
					{
						echo "<br>".$this->controller->program->text->programName.":&nbsp;";
						echo "<input type='hidden' name='".$this->form->id()."[]' value='".$program->{PGT_ID_PROGRAM_TYPE}."'/>";
						echo "<b>". $program->{PGT_PROGRAM_TYPE}."&nbsp;:&nbsp;";$targetMarket = $program -> findParentRow(CLS_TARGETMARKET); echo $targetMarket -> {TMK_TARGET_MARKET};"</b><br>";
					}
				?>
			</p>
			<div>
				<input type="submit" name="<?php echo E_CONFIRM; ?>" value="<?php echo $this->labels->confirm->button->yes;?>" />
				<input type="button" onClick="document.location='<?php echo $this->baseUrl;?><?php echo PROGRAM_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>'" value="<?php echo $this->labels->confirm->button->cancel;?>" />
			</div>
		</form>	
		<!-- =================================================================================================================== -->
		<!-- ================================================ fim do FORM ====================================================== -->
		<!-- =================================================================================================================== -->		
	</td>
</tr>
