<br>

<?php if($this->alertActivityInUse):?>
<tr>
	<td class="bigWriteRedBackground" width="100%" align="center">
		<?php printErrorsByField($this->form->idActivityDetail(), $this->alertActivityInUse);?>
	</td>
</tr>
<?php else:?>
<tr>
	<td width="100%" align="center">
		<b><?php echo $this->controller->activity->text->invalidActivity;?></b>
	</td>
</tr>
<?php endif;?>
<tr>
	<td width="100%" align="center" class="centerObject" height="40">
		<a href="<?php echo $this->baseUrl;?><?php echo ACTIVITY_DETAIL_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>"><?php echo $this->labels->button->back;?></a>
	</td>
</tr>