<?php $show = Zend_Registry::get(CONFIG)->container->income;?>
<script type="text/javascript">		
	$('#imgFakeHideInc').hide();
	<?php if($show):?>
		$().ajaxSend(function(){$('#loading3').show();});		
		$.post('<?php echo $this->baseUrl;?><?php echo INCOME_CONTROLLER;?>/<?php echo DEFAULT_CONTAINER_ACTION;?>/<?php if($this->form)echo $this->form->personId();?>/<?php if($this->form)echo $this->form->getPersonId();?>', function(data){ $('#income').append(data);$('#loading3').hide();});
	<?php else:?>
		function showIncome()
		{
			$('#maxIncome').hide();
			$('#mainIncome').show();
			$().ajaxSend(function(){$('#loading3').show();$('#imgHideInc').hide();$('#imgFakeHideInc').show();$('#tableHideInc').hide();$('#tableFakeHideInc').show();});		
			$.post('<?php echo $this->baseUrl;?><?php echo INCOME_CONTROLLER;?>/<?php echo DEFAULT_CONTAINER_ACTION;?>/<?php if($this->form)echo $this->form->personId();?>/<?php if($this->form)echo $this->form->getPersonId();?>', 
				function(data)
				{ 
					if(data.search(/<?php echo $this->labels->login->title;?>/i) != -1)
					{
						window.location.reload();
					}
					else
					{
						$('#income').append(data);
						$('#loading3').hide();
						$('#imgFakeHideInc').hide();
						$('#imgHideInc').show();
						$('#tableFakeHideInc').hide();
						$('#tableHideInc').show();
					}
				}
			);
				
		}
		
		function hideIncome()
		{
			$('#maxIncome').show();
			$('#income').empty();
			$('#mainIncome').hide();
		}
	<?php endif;?>
	
</script>

<?php if(!$show):?>
<div id="maxIncome" class="health">
	<table class="income" width="100%">
		<tr>
			<td>
				
				<table width="100%" class="tableContainer" onClick="showIncome()">
					<tr>
						<td width="10%" class="fontContainer">
							<img src="<?php echo $this->baseUrl;?>/public/images/show.png" title="<?php echo $this->labels->title->show;?>"/>
						</td>				
						<td width="90%" class="fontContainer">
							<b><?php echo $this->labels->title->income;?></b>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</div>
<?php endif;?>

<div id="mainIncome" <?php if(!$show):?>style="display: none;"<?php endif;?>>
	<table class="income" width="100%">
		<tr>
			<td class="container">
				
				<?php if(!$show):?>
					<table width="100%" class="tableContainer" id="tableHideInc" onClick="hideIncome()">
						<tr>
							<td width="10%" class="fontContainer">
								<img id="imgHideInc" src="<?php echo $this->baseUrl;?>/public/images/hide.png" title="<?php echo $this->labels->title->hide;?>"/>
								<img id="imgFakeHideInc" src="<?php echo $this->baseUrl;?>/public/images/hide.png" title="<?php echo $this->labels->title->hide;?>"/>
							</td>				
							<td width="90%" class="fontContainer">
								<b><?php echo $this->labels->title->income;?></b>
							</td>
						</tr>
					</table>
					<table width="100%" class="tableContainer" id="tableFakeHideInc">
						<tr>
							<td width="10%" class="fontContainer">
								<img id="imgHideInc" src="<?php echo $this->baseUrl;?>/public/images/hide.png" title="<?php echo $this->labels->title->hide;?>"/>								
							</td>				
							<td width="90%" class="fontContainer">
								<b><?php echo $this->labels->title->income;?></b>
							</td>
						</tr>
					</table>
				<?php else:?>
					<table width="100%" class="tableContainer">
						<tr>
							<td width="10%" class="fontContainer">								
							</td>				
							<td width="90%" class="fontContainer">
								<b><?php echo $this->labels->title->income;?></b>
							</td>
						</tr>
					</table>
				<?php endif;?>
				<p>				
				<div id="loading3">
					<center><img src="<?php echo $this->baseUrl;?>/public/images/loading.gif"/></center>
				</div>
				<div id="income"></div>
												
			</td>
		</tr>
	</table>
</div>