
<table width="100%">
	<form action="<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_EDIT_ACTION;?>" method="post">
		<tr>
			<td  colspan="2">
				<h1><?php echo $this->controller->region->title->editRegion;?></h1>
			</td>
		</tr>
		<tr>
			<td width="15%">
				<b><?php echo $this->controller->region->title->name;?>:</b>
			</td>
			<td>
				<input size="30" type="text" name="<?php echo RegionForm::region()?>" value="<?php if($this->form->getRegion()) echo $this->form->getRegion(); else echo $this->region->{RGN_REGION};?>"><br>
				<?php printErrorsByField($this->form->region(), $this->errorMessages); ?>
				<input type="hidden" name="<?php echo RegionForm::idRegion()?>" value="<?php echo $this->region->{RGN_ID_REGION};?>"/>
				<?php printErrorsByField($this->form->idRegion(), $this->errorMessages); ?>
			</td>
		</tr>
		<!-- estado -->
		<tr>
			<td  colspan="2">
				<b><?php echo $this->controller->region->text->state;?></b>
			</td>
		</tr>
		<tr>
			<td colspan="2">				
				<?php echo $this->form->getState();?>
			</td>
		</tr>
		<!-- cidades -->
		<tr>
			<td  colspan="2">
				<b><?php echo $this->controller->region->text->city;?></b>				
			</td>
		</tr>
		<tr>
			<td colspan="2">				
				<?php echo $this->city;?>						
				<input type="hidden" name="<?php echo $this->form->city();?>" value="<?php echo $this->form->getCity();?>">	
			</td>
		</tr>
		<tr>
			<td  colspan="2">
				<b><?php echo $this->controller->region->text->editNeighborhood;?></b>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<?php printErrorsByField($this->form->neighborhood(), $this->errorMessages); ?>
				<?php if($this->region) $nbhRegion = $this->region->findDependentRowset(CLS_NEIGHBORHOODREGION); ?>
				<table width="100%" class="noBorder">
					<tr>
						<td width="45%">
							<b><?php echo $this->controller->region->text->option;?></b><br>
							<select class="slctRegion" multiple="" name="" id="listOptions" ondblclick="moveSelectedOptions(this.form['listOptions'],this.form['changeLog.reasonIds'],true);selected(this.form['changeLog.reasonIds']);">
								<?php foreach($this->neighborhoods as $neighborhood) { $flag = false;?>
									<?php foreach($nbhRegion as $nbh): ?>
										<?php if($nbh->{NHD_ID_NEIGHBORHOOD} == $neighborhood->{NHD_ID_NEIGHBORHOOD}){ $flag = true; break;}?>										
									<?php endforeach;?>
									<?php if($flag === false):?>
										<option value="<?php echo $neighborhood->{NHD_ID_NEIGHBORHOOD}?>" id="listOptions1" title="<?php echo $neighborhood->{NHD_NEIGHBORHOOD}?>"><?php echo $neighborhood->{NHD_NEIGHBORHOOD}?></option>
									<?php endif;?>
								<?php }?>
							</select>
						</td>
						<td width="0%" align="center">
							<p> &nbsp; </p>
							<p><input type="button" style="width: 1cm;" value="&gt;" onclick="moveSelectedOptions(this.form['listOptions'],this.form['changeLog.reasonIds'],true);selected(this.form['changeLog.reasonIds']);" name="ad"/></p>
							<p><input type="button" style="width: 1cm;" value="&gt;&gt;" onclick="moveAllOptions(this.form['listOptions'],this.form['changeLog.reasonIds'],true);selected(this.form['changeLog.reasonIds']);" name="adAll"></p>
							<p><input type="button" style="width: 1cm;" value="&lt;&lt;" onclick="moveAllOptions(this.form['changeLog.reasonIds'],this.form['listOptions'],true);selected(this.form['changeLog.reasonIds']);" name="remAll"></p>
							<p><input type="button" style="width: 1cm;" value="&lt;" onclick="moveSelectedOptions(this.form['changeLog.reasonIds'],this.form['listOptions'],true);selected(this.form['changeLog.reasonIds']);" name="rem"/></p>
						</td>
						<td width="45%">							
							<b><?php echo $this->controller->region->text->include;?></b><br>
							<select class="slctRegion" multiple="" name="<?php echo RegionForm::neighborhood();?>[]" id="changeLog.reasonIds" ondblclick="moveSelectedOptions(this.form['changeLog.reasonIds'],this.form['listOptions'],true)">
							<?php foreach($nbhRegion as $current) 
								{
								$neighborhood = $current->findParentRow(CLS_NEIGHBORHOOD); 
							?>
								<option value="<?php echo $neighborhood->{NHD_ID_NEIGHBORHOOD};?>" id="listOptions1" title="<?php echo $neighborhood->{NHD_NEIGHBORHOOD}?>"><?php echo $neighborhood->{NHD_NEIGHBORHOOD};?></option>
							<?php } ?>
							</select>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="submit" value="<?php echo $this->labels->button->save;?>" onClick="selected(this.form['changeLog.reasonIds']);"/>
				<input type="button" value="<?php echo $this->labels->button->back;?>" onClick="document.location='<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>'">				
			</td>
		</tr>
	</form>
</table>