<?php
/*
 * Created on 12/03/2008
 * Author: Jefferson
 */
?>
<table width="100%">
	<tr>
		<td colspan="3">
			<h1><?php echo $this->controller->region->title->listRegion;?></h1>
		</td>
	</tr>
	<tr>
		<td>
			<?php printErrorsByField($this->form->idRegion(), $this->errorMessages); ?>
		</td>
		<td align="right" colspan="2">
			|&nbsp;<a href="<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_NEW_ACTION;?>"><?php echo $this->controller->region->button->newRegion;?></a>&nbsp;|
		</td>
	</tr>
	<?php $i=0; foreach($this->regions as $region) {?>
		<form name="frm<?php echo $i;?>" method="post">
		<tr>
			<td width="60%">
				<?php echo $region->{RGN_REGION}?>
				<input type="hidden" name="<?php echo RegionForm::idRegion();?>" value="<?php echo $region->{RGN_ID_REGION};?>">
			</td>
			<td width="15%">				
				<a href="javascript: document.frm<?php echo $i;?>.action='<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_VIEW_ACTION;?>'; document.frm<?php echo $i;?>.submit();">
					<?php echo $this->labels->button->edit;?>
				</a>
			</td>
			<td width="15%">				
				<a href="javascript: document.frm<?php echo $i;?>.action='<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_CONFIRM_ACTION;?>'; document.frm<?php echo $i;?>.submit();">
					<?php echo $this->labels->button->drop;?>
				</a>
			</td>
		</tr>
		</form>
	<?php $i++;  }?>
</table>
