<?php echo $this->render('header/header.phtml');?>								 		  						
				  
<!-- ===================================== -->
<!-- inicio : específico com cada template -->					
<!-- ===================================== -->						  
<div>
	<?php echo $this->render('submenu/submenuAdm.phtml');?>

	<?php echo $this->render('success/_success.phtml');?>
	<a href="<?php echo $this->baseUrl;?><?php echo REGION_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>">Voltar</a>
</div>																  
<!-- ================================== -->
<!-- fim : específico com cada template -->					
<!-- ================================== -->		

<?php echo $this->render('footer/footer.phtml');?>


