<tr>
	<td width="100%" align="center">
		<h1>
			<?php echo ($this->labels->confirm->disable->title);?>
		</h1>
		<!-- =================================================================================================================== -->
		<!-- =================================== FORM utilizado para excluir uma ou mais classificações ======================== -->
		<!-- =================================================================================================================== -->
		<form action="<?php echo $this->baseUrl;?><?php echo CLASSIFICATION_CONTROLLER;?>/<?php echo $this->action;?>" method="post">
			<p>
				<?php echo $this->labels->confirm->disable->text;?>&nbsp;?<br>
				<?php 
					foreach($this->objectClassifications as $classification)
					{
						echo "<br>".$this->controller->classification->text->classificationName.":&nbsp;";
						echo "<input type='hidden' name='".$this->form->id()."[]' value='".$classification->{ECT_ID_ENTITY_CLASSIFICATION}."'/>";
						echo "<b>". $classification->{ECT_ENTITY_CLASSIFICATION}."</b><br>";
					}
				?>
			</p>
			<div>
				<input type="submit" name="<?php echo E_CONFIRM; ?>" value="<?php echo $this->labels->confirm->button->yes;?>" />
				<input type="button" onClick="document.location='<?php echo $this->baseUrl;?><?php echo CLASSIFICATION_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>'" value="<?php echo $this->labels->confirm->button->cancel;?>" />
			</div>
		</form>	
		<!-- =================================================================================================================== -->
		<!-- ================================================ fim do FORM ====================================================== -->
		<!-- =================================================================================================================== -->		
	</td>
</tr>
