<table width="100%" class="withoutEdge">
	<?php printErrorsByField($this->form->id(), $this->errorMessages);?>
	<tr>
		<td class="bold">
			<table class="borderBlack" width="100%">
				<!-- =================================================================================================================== -->
				<!-- ============== FORM utilizado para persistir um perfil:  salvar e editar um pefil ================================= -->
				<!-- =================================================================================================================== -->
				<form action="<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php if($this->escape($this->form->getId()) != null){echo DEFAULT_EDIT_ACTION;}else{echo DEFAULT_ADD_ACTION;}?>" method="post">
					<tr>
						<td colspan="4">
							<h1><?php echo $this->controller->profile->title->registerProfile;?></h1>
						</td>
					</tr>
					<tr>
						<td width="20%" class="bold">
							<?php echo $this->controller->profile->text->profileName;?>:
						</td>
						<td width="50%">
							<input type="hidden" value="<?php echo $this->escape($this->form->getId());?>" name="<?php echo $this->form->id();?>"/>
							<input type="text" size="50" name="<?php echo ProfileForm::profileName();?>"  value="<?php echo $this->escape($this->form->getProfileName());?>" />
						</td>
						<td width="20%">
							<select name="<?php echo $this->form->status();?>">
								<option value="<?php echo Constants::ENABLE;?>" <?php if($this->form->getStatus() == Constants::ENABLE) echo "selected";?>><?php echo $this->labels->text->enable;?></option>
								<option value="<?php echo Constants::DISABLE;?>" <?php if($this->form->getStatus() == Constants::DISABLE) echo "selected";?>><?php echo $this->labels->text->disable;?></option>
							</select>
						</td>
						<td width="10%">
							<input class="small" type="submit" value="<?php echo $this->labels->button->save;?>"/>
						</td>
					</tr>
					<tr>
						<td >&nbsp;</td>
						<td ><?php printErrorsByField($this->form->profileName(), $this->errorMessages);?></td>
							<td colspan="2">
							<?php printErrorsByField($this->form->status(), $this->errorMessages);?>
						</td>
					</tr>
				</form>
				<!-- ================================================================================================================== -->
				<!-- ======================================================== fim do FORM ============================================= -->
				<!-- ================================================================================================================== -->
			</table>
			<br><br>
		</td>
	</tr>

	<tr>
		<td class="bold">
			<!-- =================================================================================================================== -->
			<!-- ===================== FORM utilizado para carregar um ou mais perfis para ser excluído ============================ -->
			<!-- ========================= FORM utilizado para carregar um perfil para ser editado ================================= -->
			<!-- =================================================================================================================== -->
			<form id="<?php echo PROFILE_FORM;?>" method="post">
				<table class="borderBlack" width="100%">
					<tr>
						<td colspan="2">
							<h1><?php echo $this->controller->profile->title->manage;?></h1>
						</td>
					</tr>
					<tr>
						<td width="20%" class="bold">
							<?php echo $this->controller->profile->text->listProfile;?>:
						</td>
						<td width="80%" colspan="2">
							<select id="typeProfile" name="<?php echo $this->form->id();?>[]" size="10" multiple>
								<?php 
									foreach($this->profiles as $profile)
									{
										echo "<option value='".$profile->{AUTH_ID_PROFILE}."' title='".$profile->{AUTH_PROFILE}."'>".$profile->{AUTH_PROFILE};
										if($profile->{AUTH_STATUS} == Constants::DISABLE)
											echo "&nbsp;*&nbsp;".$this->labels->text->disable."&nbsp;*";
										echo "</option>";
									}
								?>
							</select>
						</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td class="alignLeft">
							<input type="submit" value="<?php echo $this->labels->button->edit;?>" 
							onClick="javascript: return reportMultipleSelected('<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo DEFAULT_VIEW_ACTION;?>',this.form, 'typeProfile');">
							<input type="submit" value="<?php echo $this->labels->button->disable;?>" 
							onClick="javascript: return actionName('<?php echo $this->baseUrl;?><?php echo PROFILE_CONTROLLER;?>/<?php echo DEFAULT_CONFIRM_ACTION;?>',this.form);">
						</td>
					</tr>
				</table>
			</form>
			<!-- =================================================================================================================== -->
			<!-- ======================================================== fim do FORM ============================================== -->
			<!-- =================================================================================================================== -->
		</td>
	</tr>
</table>
