<form action="<?php echo $this->baseUrl;?><?php echo USER_CONTROLLER;?>/<?php echo DEFAULT_CHANGE_PASSWORD_ACTION;?>" method="post">
	<table class="user" width="98%">
		<tr>
			<td colspan="2" height="30">
				<?php echo $this->helpcontroller->user2?>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<h1><?php echo $this->controller->user->text->alterPass->password;?></h1>
			</td>
		</tr>
		<tr>
			<td class="alignRight" width="20%">
				<?php echo $this->controller->user->text->currentPass->password;?>:
			</td>
			<td width="80%">
				<input class="changePassword" maxlength="32" type="password" name="<?php echo $this->form->oldPassword();?>" value="<?php echo $this->form->getOldPassword();?>"/>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><?php printErrorsByField($this->form->oldPassword(), $this->errorMessages);?></td>
		</tr>
		
		<tr>
			<td class="alignRight">
				<?php echo $this->controller->user->text->newPass->password;?>:
			</td>
			<td>
				<input class="changePassword" maxlength="32" type="password" name="<?php echo $this->form->password();?>" value="<?php echo $this->form->getPassword();?>"/>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><?php printErrorsByField($this->form->password(), $this->errorMessages);?></td>
		</tr>
		
		<tr>
			<td class="alignRight">
				<?php echo $this->controller->user->text->repeatPass->password;?>:
			</td>
			<td>
				<input class="changePassword" maxlength="32" type="password" name="<?php echo $this->form->repeatPassword();?>" value="<?php echo $this->form->getRepeatPassword();?>"/>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td><?php printErrorsByField($this->form->repeatPassword(), $this->errorMessages);?></td>
		</tr>
	</table>
	<br>
	<input type="button" onClick="history.go(-1)" value="<?php echo $this->labels->button->back;?>"/>&nbsp;&nbsp;&nbsp;<input type="submit" value="<?php echo $this->labels->button->save;?>"/>
</form>