<?php echo $this->render('header/container.phtml');?>
<table class="icontainer" width="98%">
	<?php $levelInstruction = $this->levelInstruction;?>
	<tr>
		<td>
			<b><?php echo $this->controller->health->container->vaccination;?></b>
		</td>
		<td>
			<?php 
				if($this->healthByPerson->{HLT_VACCINE_TO_DATE})
				{
					if($this->healthByPerson->{HLT_VACCINE} == 1)
					{
						echo $this->labels->text->not;
					}
					else
					{
						echo $this->labels->text->not;
					}					
				}
				else
				{
					echo $this->labels->text->nodata;
				}
			?>
		</td>
	</tr>
	<tr>
		<td><b><?php echo $this->controller->health->container->information; ?>:</b>
		</td>
		<td>
			<?php
				if($this->healthByPerson->{HLT_VACCINE_TO_DATE})
				{
					echo $this->form->dateFormatForm($this->healthByPerson->{HLT_VACCINE_TO_DATE});
				}			
			?>
		</td>
	</tr>
	<tr>
		<td>
			<b><?php echo $this->controller->health->container->agreement;?></b>
		</td>
		<td>
			<?php 
				if(sizeof($this->healthByPerson) <= 0)
				{
					echo $this->labels->text->nodata;
				}
				elseif($this->healthByPerson->{HLT_HEALTH_PLAN} != null)
				{
					echo $this->healthByPerson->{HLT_HEALTH_PLAN};
				}
				else
				{
					echo $this->labels->text->not;
				}
			?>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<input class="small" type="submit" onclick="parent.document.location='<?php echo $this->baseUrl;?><?php echo HEALTH_CONTROLLER;?>/<?php echo DEFAULT_INDEX_ACTION;?>/<?php if($this->form)echo $this->form->personId();?>/<?php if($this->form)echo $this->form->getPersonId();?>'" value="<?php echo $this->labels->button->showDetail;?>"/>
		</td>
	</tr>
</table>
